# Setup
title:        Genomic pipelines in Kundaje lab
tagline:      BigDataScript pipelines, libraries and programming guideline
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jin Lee and Anshul Kundaje
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
